services:
  - type: web
    name: tripl3sixmafia-crypter-api
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/index.js
    region: oregon 
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 5
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  - type: static
    name: tripl3sixmafia-crypter-static
    buildCommand: npm install && npm run build
    publishDir: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          name: tripl3sixmafia-crypter-api
          type: web
          property: url
    autoDeploy: true