services:
  - type: web
    name: tripl3sixmafia-crypter
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    region: oregon 
    plan: free
    healthCheckPath: /api/health
    healthCheckTimeout: 5
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true