services:
  - type: web
    name: tripl3sixmafia-crypter
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/index.js
    region: oregon # or choose a region closer to your users
    plan: free # can be upgraded later
    healthCheckPath: /
    healthCheckTimeout: 5
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    domains:
      - tripl3sixmafia-crypter.onrender.com # This will be auto-assigned by Render